import Logo from "./components/Logo";
import Navigation from "./components/navigation";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Logo />
        <Navigation />
        {children}
        <footer>Just A dummy Footer</footer>
      </body>
    </html>
  );
}
