import Logo from "./_components/Logo";
import Navigation from "./_components/Navigation";
import "@/app/_styles/globals.css";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-blue-800">
        <Logo />
        <Navigation />
        {children}
        <footer>Just A dummy Footer</footer>
      </body>
    </html>
  );
}
